# Generated by Django 4.1.7 on 2023-03-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="guest_can_pause",
            new_name="newspaper",
        ),
        migrations.RemoveField(
            model_name="room",
            name="code",
        ),
        migrations.RemoveField(
            model_name="room",
            name="host",
        ),
        migrations.RemoveField(
            model_name="room",
            name="votes_to_skip",
        ),
        migrations.AddField(
            model_name="room",
            name="electrical_bill",
            field=models.CharField(default="", max_length=8),
        ),
        migrations.AddField(
            model_name="room",
            name="flight_4_over",
            field=models.CharField(default="", max_length=8),
        ),
        migrations.AddField(
            model_name="room",
            name="flight_4_under",
            field=models.CharField(default="", max_length=8),
        ),
        migrations.AddField(
            model_name="room",
            name="gas_bill",
            field=models.CharField(default="", max_length=8),
        ),
        migrations.AddField(
            model_name="room",
            name="mileage_bill",
            field=models.CharField(default="", max_length=8),
        ),
        migrations.AddField(
            model_name="room",
            name="oil_bill",
            field=models.CharField(default="", max_length=8),
        ),
        migrations.AddField(
            model_name="room",
            name="recycle",
            field=models.BooleanField(default=False),
        ),
    ]
